services:
  backend:
    image: infotrack/project-waterloo-backend
    container_name: backend
    build:
      context: waterloo/backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    image: infotrack/project-waterloo-frontend
    container_name: frontend
    ports:
      - "80:8080"
    build:
      context: waterloo/frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=backend:8080